# Generated by Django 2.0 on 2018-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeats', '0002_auto_20180317_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuClass_int',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuNumber_int',
            field=models.IntegerField(blank=True),
        ),
    ]
