# Generated by Django 2.0 on 2018-03-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeats', '0003_auto_20180317_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='BackTime_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='ContactPhone_bigint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Contact_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Destination_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='LeaveTime_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuClass_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuName_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuNumber_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuPhone_bigint',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
