# Generated by Django 2.0 on 2018-03-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeats', '0005_leaveinfo_isleaving_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='BackTime_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='ContactPhone_bigint',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Contact_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Destination_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='LeaveTime_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='StuPhone_bigint',
            field=models.BigIntegerField(null=True),
        ),
    ]
