# Generated by Django 2.0 on 2018-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exeats', '0006_auto_20180330_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='HolidayDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
